// src/app/ui/dom.js

(function(global) {
    global.App = global.App || {};
    global.App.UI = global.App.UI || {};
    global.App.UI.DOM = {
        chatHistory: 'chat-history',
        chatInput: 'chat-input',
        btnSend: 'btn-send',
        btnStop: 'btn-stop',
        btnClear: 'btn-clear-chat',
        aiTyping: 'ai-typing',
        filePreviewArea: 'file-preview-area',
        chatFileUpload: 'chat-file-upload',
        chatResizer: 'chat-resizer',
        sidebar: 'sidebar',
        fileExplorer: 'file-explorer',
        explorerResizer: 'explorer-resizer',
        folderUpload: 'folder-upload',
        filesUpload: 'files-upload',
        contextUploadInput: 'context-upload-input',
        btnDownload: 'btn-download',
        btnImportBackup: 'btn-import-backup',
        importBackupInput: 'import-backup-input',
        storageUsageBar: 'storage-usage-bar',
        storageUsageText: 'storage-usage-text',
        contextMenu: 'context-menu',
        previewFrame: 'preview-frame',
        previewLoader: 'preview-loader',
        btnRefresh: 'btn-refresh',
        editorOverlay: 'editor-overlay',
        codeEditor: 'code-editor',
        editorFilename: 'editor-filename',
        btnCloseEditor: 'btn-close-editor',
        btnSaveEditor: 'btn-save-editor',
        mediaOverlay: 'media-overlay',
        mediaImage: 'media-image',
        btnCloseMedia: 'btn-close-media',
        mediaFilename: 'media-filename',
        apiKey: 'api-key',
        btnSaveKey: 'btn-save-key',
        modelStatus: 'model-status',
        saveStatus: 'save-status',
        resizeOverlay: 'resize-overlay',
        btnBackup: 'btn-backup',
        btnHistory: 'btn-history',
        btnReset: 'btn-reset',
        historyModal: 'history-modal',
        btnCloseModal: 'btn-close-modal',
        snapshotList: 'snapshot-list',
        btnCreateSnapshot: 'btn-create-snapshot',
        btnDeleteAllSnapshots: 'btn-delete-all-snapshots',
        mobileNavFiles: 'mobile-nav-files',
        mobileNavView: 'mobile-nav-view',
        mobileNavChat: 'mobile-nav-chat',
        mobileOverlay: 'mobile-overlay',
        chatPanel: 'chat-panel'
    };
})(window);